export default {
  Inter_400Regular: require('../assets/fonts/Inter_400Regular.ttf'),
  Inter_500Medium: require('../assets/fonts/Inter_500Medium.ttf'),
  Inter_600SemiBold: require('../assets/fonts/Inter_600SemiBold.ttf'),
  Inter_700Bold: require('../assets/fonts/Inter_700Bold.ttf'),
  Inter_300Light: require('../assets/fonts/Inter_300Light.ttf'),
  Poppins_600SemiBold: require('../assets/fonts/Poppins_600SemiBold.ttf'),
  Poppins_300Light: require('../assets/fonts/Poppins_300Light.ttf'),
  Poppins_400Regular: require('../assets/fonts/Poppins_400Regular.ttf'),
  Poppins_500Medium: require('../assets/fonts/Poppins_500Medium.ttf'),
  Poppins_700Bold: require('../assets/fonts/Poppins_700Bold.ttf'),
  Poppins_900Black: require('../assets/fonts/Poppins_900Black.ttf'),
  Poppins_500Medium_Italic: require('../assets/fonts/Poppins_500Medium_Italic.ttf'),
  Rasa_300Light_Italic: require('../assets/fonts/Rasa_300Light_Italic.ttf'),
  Rasa_400Regular: require('../assets/fonts/Rasa_400Regular.ttf'),
  Rasa_500Medium: require('../assets/fonts/Rasa_500Medium.ttf'),
  Rasa_600SemiBold: require('../assets/fonts/Rasa_600SemiBold.ttf'),
  Rasa_300Light: require('../assets/fonts/Rasa_300Light.ttf'),
  Rasa_700Bold: require('../assets/fonts/Rasa_700Bold.ttf'),
  Rasa_500Medium_Italic: require('../assets/fonts/Rasa_500Medium_Italic.ttf'),
  Rasa_400Regular_Italic: require('../assets/fonts/Rasa_400Regular_Italic.ttf'),
  Rasa_700Bold_Italic: require('../assets/fonts/Rasa_700Bold_Italic.ttf'),
};
